"""Increase password hash length

Revision ID: 70418c10b0c3
Revises: 8a3b9a8acf50
Create Date: 2025-10-18 21:56:32.268022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70418c10b0c3'
down_revision = '8a3b9a8acf50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
